### ISSUE TITLE
Occurrence are not being paged, so only the first page is used.

### ISSUE THREAD

**Issue by MortenHofft** [gbif/mgnify-to-dwc#2]
As far as I can see the current implementation doesn't page through the occurrences. It is often the case that there is more than one page, although most only have one.

**Comment by thomasstjerne** [comment]
Notice the recursion: https://github.com/gbif/mgnify-to-dwc/blob/9c9d17f4722bedd0f2104738c9521c64fb408bfd/index.js#L233

**Comment by thomasstjerne** [comment]
2000+ occurrences on this event: https://www.gbif-uat.org/dataset/9bca5c6e-92cc-4a6b-8448-d05ca560d272/event/ERS492617
