### ISSUE TITLE
Reconsider what analyses to use

### ISSUE THREAD

**Issue by MortenHofft** [gbif/mgnify-to-dwc#3]
The current implementation only use the first analyses for a sample ID. I think it is worth investigating if that is a good choice. I'm sceptical because:

* there can be 2 analyses of the same sample ID that has very different amount of occurrences (say differ by 50%) - why choose the first in the API and not the second?
* 2 analyses of the same sample can share the same timestamp, but vary in instrument description and have different occurrence data.
* In case of study MGYS00002376 all 2716 analyses are from the same day with many duplicated sampleIDs - but we discard the majority because we only consider the first mention if a sampleID.

Having the data in UAT as we do now seems to be a good starting point for discussing this with the Mgnify group - unless we already have answers of course.

**Comment by thomasstjerne** [comment]
Closing as we are now using analyses as samples, despite it is duplicating some data.
