### ISSUE TITLE
Bring into production

### ISSUE THREAD

**Issue by MattBlissett** [gbif/mgnify-to-dwc#4]
We need a production deployment, but we still need a UAT setup, so we can test changes (e.g. after the missing data is exposed in the API).

1. Decide how UAT and production should be set up.  Are they two processes that publish independently, or is it one process that can be set to publish to UAT, and then somehow transfer the results (possibly after review) to production?

2. Work out how to register the datasets.  I don't see the results of the `register.sh` example script on the labs VM — was it used?  A dataset's UUID needs to be stored upon registration, so changes can be made and ingestions triggered.  The Bash script is a rough script with no error checking, it shouldn't be used unattended. 

3. Choose where this runs, e.g. labs, Jenkins, another VM. The choice depends on how often it runs, and perhaps the decision on ①. Jenkins can run scheduled tasks nicely, and keep a record of the output.  Cron isn't great at keeping output, but it's easier to preserve state (e.g. a record of UUIDs can go in a file with less risk of it being lost).

4. Choose where the published result ends up. This is of very little importance; dataset endpoints are an implementation detail.  Some NFS place which I will present from some webserver.

**Comment by thomasstjerne** [comment]
As discussed with @MattBlissett 
We will create a node script that registers new datasets and stores their uuids in a file (it must know the env)
We will run it at labs, UAT and PROD, will have separate path so a test can be run at UAT without updating prod

**Comment by MattBlissett** [comment]
4: The production archives can be put in `/mnt/auto/misc/hosted-datasets.gbif.org/mgnify/` (accessible from labs-vh), it will be available on https://hosted-datasets.gbif.org/ and backup up with the usual procedures. A UUID state file(s) could go here too, then it's backed up with the data.

The test/UAT datasets don't matter, http://labs.gbif.org/~mhoefft/mgnify/ is fine, or else `/var/www/html/mgnify` (or a symlink) on labs if you don't like seeing Morten's name in the URL.
