### ISSUE TITLE
If coordinates are missing, see if country is in "geographic location (country and/or sea,region)" 

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/mgnify-to-dwc#6]
May be specific for this dataset: https://www.gbif.org/dataset/c1d8da29-9126-4e11-a699-722bd3d7492f

**Comment by ManonGros** [comment]
This other dataset is similar: https://www.gbif.org/dataset/4f05727d-ba08-44bd-b35d-b1d9d20ca2ef

**Comment by thomasstjerne** [comment]
Expect values to contain data in the format: "USA: Miami, Florida", "China: LIAONING"

i.e. use first part (before colon) as country, second part as location
